services:
  db:
    image: postgres:16-alpine
    container_name: sportsdb-db
    restart: unless-stopped
    environment:
      PG_DB: ${PG_DB:-sportsdb}
      PG_USER: ${PG_USER:-sportsdb}
      PG_PASSWORD: ${PG_PW:-change-me}
    ports:
      - "${PG_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      # pg_isready = Postgres tool which checks whether the db server is already accepting connections
      # :- = [if the envvar is known, use it; otherwise use the default on the right]
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER:-sportsdb} -d ${PG_DB:-sportsdb}"]
      # start_period: 20s
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: ../server
    container_name: sportsdb-api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg://${PG_USER:-sportsdb}:${PG_PW:-change-me}@db:5432/${PG_DB:-sportsdb}

volumes:
  db_data:

